"use client";

import { useEffect, useId, useState } from "react";

interface Props {
  code: string;
}

export function MermaidBlock({ code }: Props) {
  const id = useId().replace(/:/g, "_");
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setSvg(null);
    setError(false);

    (async () => {
      try {
        const { default: mermaid } = await import("mermaid");
        const isDark =
          typeof document !== "undefined" &&
          document.documentElement.classList.contains("dark");
        mermaid.initialize({
          startOnLoad: false,
          theme: isDark ? "dark" : "neutral",
          securityLevel: "strict",
        });
        const { svg: rendered } = await mermaid.render(`mermaid_${id}`, code);
        if (!cancelled) setSvg(rendered);
      } catch {
        if (!cancelled) setError(true);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, id]);

  if (error) {
    return (
      <pre className="overflow-x-auto rounded bg-muted/50 p-3 text-xs font-mono text-muted-foreground">
        {code}
      </pre>
    );
  }

  if (!svg) {
    return (
      <div className="flex items-center gap-2 py-2 text-xs text-muted-foreground">
        <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" />
        渲染图表中…
      </div>
    );
  }

  return (
    <div
      className="my-2 overflow-x-auto rounded-lg bg-white dark:bg-zinc-900 p-3"
      // svg is generated by mermaid — safe, no user-controlled content injected
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
